### ISSUE TITLE
Erro no projeto exemplo disponibilizado, signer-examples

### ISSUE THREAD

**Issue by mardeniferreira** [demoiselle/signer#137]
Prezados,

O código de exemplo disponibilizado por vocês (projeto signer-examples), mais abaixo, estava funcionando normalmente. Inclusive, havia assinado alguns arquivos com o emprego de um certificado armazenado num token GD Star Sign. No entanto, semana passada, ao tentar executar o código, a seguinte exceção foi levantada. Não estou conseguindo desvendar a raiz do problema. Tentei rodar o código na versão anterior e na versão mais recente do Demoiselle Signer, 3.2.2 e 3.2.3, respectivamente, sem sucesso. 

**Observação 1:** O Token está completamente funcional pois consigo assinar documentos através de outras ferramentas.

**Observação 2:** antes de estourar a exceção, a seguinte mensagem foi exibida no console "WARN  PolicyValidator:51 - A Lista de políticas de assinatura do componente para o padrão usado está desatualizada, a data de atualização é: 20/02/2018 - 09:00:00"; já tentei ver se tem uma política mais recente como por exemplo AD_RT_CADES_2_3, mas não encontrei tal política.

Gostaria que vocês nos dessem um norte, pois aqui na UFPE estamos desenvolvendo uma extensão para assinatura digital no Chrome, através de Native Messaging, consumindo um módulo nativo baseado no Demoiselle Signer. A solução estava funcionando até o estouro desse erro e não sabemos como resolver o problema.

**StackTrace da Exceção:**

`mar 08, 2018 5:05:46 PM org.demoiselle.signer.signer.examples.Signer main
INFORMAÇÕES: ============= Iniciando aplicaÃ§Ã£o =============
mar 08, 2018 5:05:46 PM org.demoiselle.signer.signer.examples.Signer sign
INFORMAÇÕES: ===== AD_RT_CADES_2_2 =====
2018-03-08 17:05:49 INFO  Configuration:167 - Driver carregado [TokenOuSmartCard_01]
**WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.demoiselle.signer.core.keystore.loader.implementation.MSKeyStoreLoader (file:/C:/Users/Mardeni/.m2/repository/org/demoiselle/signer/core/3.2.3/core-3.2.3.jar) to field java.security.KeyStore.keyStoreSpi
WARNING: Please consider reporting this to the maintainers of org.demoiselle.signer.core.keystore.loader.implementation.MSKeyStoreLoader**
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-03-08 17:05:53 INFO  CAManager:213 - Procurando certificado no Provider: Provedor OFFLINE de cadeias ICP-Brasil  (icpbrasil.jks)
2018-03-08 17:05:53 INFO  CAManager:268 - Foram encontrados 4 níveis na cadeia do provider Provedor OFFLINE de cadeias ICP-Brasil  (icpbrasil.jks) 
2018-03-08 17:05:53 INFO  BasicCertificate:568 - Adicionando a url http://repositorio.serpro.gov.br/lcr/acserproacfv4.crl
2018-03-08 17:05:53 INFO  BasicCertificate:568 - Adicionando a url http://certificados2.serpro.gov.br/lcr/acserproacfv4.crl
2018-03-08 17:05:53 INFO  BasicCertificate:568 - Adicionando a url http://repositorio.icpbrasil.gov.br/lcr/serpro/acserproacfv4.crl
2018-03-08 17:05:54 INFO  OnLineCRLRepository:85 - Foi encontrada uma LCR válida: http://repositorio.serpro.gov.br/lcr/acserproacfv4.crl
2018-03-08 17:05:54 INFO  CAdESSigner:588 - OID do algoritmo que irá gerar assinatura: 1.2.840.113549.1.1.11
2018-03-08 17:05:54 INFO  CAdESSigner:589 - Nome do  algoritmo que irá gerar a assinatura : SHA256withRSA
2018-03-08 17:05:54 INFO  CAdESSigner:591 - Algoritmo padrão contido na política:  1.2.840.113549.1.1.11
2018-03-08 17:05:54 INFO  CAdESSigner:593 - Tamanho mínimo para chave:  2.048
2018-03-08 17:05:54 INFO  CAdESSigner:596 - Validando o tamanho da chave.
2018-03-08 17:05:54 INFO  CAdESSigner:608 - Efetuando a verificação dos atributos assinados
2018-03-08 17:05:54 INFO  AttributeFactory:68 - Consultando o atributo com OID [1.2.840.113549.1.9.3]
2018-03-08 17:05:54 INFO  AttributeFactory:73 - Retornando o atributo : org.demoiselle.signer.policy.impl.cades.pkcs7.attribute.impl.ContentType
2018-03-08 17:05:54 INFO  AttributeFactory:68 - Consultando o atributo com OID [1.2.840.113549.1.9.4]
2018-03-08 17:05:54 INFO  AttributeFactory:73 - Retornando o atributo : org.demoiselle.signer.policy.impl.cades.pkcs7.attribute.impl.MessageDigest
2018-03-08 17:05:54 INFO  AttributeFactory:68 - Consultando o atributo com OID [1.2.840.113549.1.9.16.2.47]
2018-03-08 17:05:54 INFO  AttributeFactory:73 - Retornando o atributo : org.demoiselle.signer.policy.impl.cades.pkcs7.attribute.impl.SigningCertificateV2
2018-03-08 17:05:54 INFO  AttributeFactory:68 - Consultando o atributo com OID [1.2.840.113549.1.9.16.2.15]
2018-03-08 17:05:54 INFO  AttributeFactory:73 - Retornando o atributo : org.demoiselle.signer.policy.impl.cades.pkcs7.attribute.impl.IdSigningPolicy
2018-03-08 17:05:54 INFO  CAdESSigner:640 - Ponto de Confiança ... CN=Autoridade Certificadora Raiz Brasileira v5, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
2018-03-08 17:05:54 INFO  CAdESSigner:640 - Ponto de Confiança ... CN=Autoridade Certificadora Raiz Brasileira v2, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
2018-03-08 17:05:54 INFO  CAdESSigner:652 - CN=Autoridade Certificadora SERPRO v3, OU=Autoridade Certificadora Raiz Brasileira v2, O=ICP-Brasil, C=BR
2018-03-08 17:05:54 INFO  CAdESSigner:652 - CN=Autoridade Certificadora Raiz Brasileira v2, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
2018-03-08 17:05:54 INFO  CAdESSigner:652 - CN=Autoridade Certificadora Raiz Brasileira v2, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
2018-03-08 17:05:54 INFO  CAdESSigner:652 - CN=Autoridade Certificadora do SERPRO Final v4, OU=Servico Federal de Processamento de Dados - SERPRO, OU=CSPB-1, O=ICP-Brasil, C=BR
2018-03-08 17:05:54 INFO  CAdESSigner:658 - O certificado pertence a cadeia CN=Autoridade Certificadora Raiz Brasileira v2, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR que é permitida pela política  para gerar a assinatura.
2018-03-08 17:05:54 INFO  CAdESSigner:668 - Verificando o período de validade da politica
2018-03-08 17:05:54 WARN  PolicyValidator:51 - A Lista de politicas de assinatura do componente para o padrão usado está desatualizada, a data de atualização é: 20/02/2018 - 09:00:00
2018-03-08 17:05:54 INFO  CAdESSigner:361 - Adicionando Certificado no CertStore
2018-03-08 17:05:54 INFO  CAdESSigner:676 - OID do algoritmo que irá gerar assinatura: 1.2.840.113549.1.1.11
Exception in thread "main" org.demoiselle.signer.policy.impl.cades.SignerException: org.bouncycastle.operator.OperatorCreationException: cannot create signer: Supplied key (null) is not a RSAPrivateKey instance
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:779)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:506)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doAttachedSign(CAdESSigner.java:794)
	at org.demoiselle.signer.signer.examples.Signer.sign(Signer.java:88)
	at org.demoiselle.signer.signer.examples.Signer.main(Signer.java:38)
Caused by: org.bouncycastle.operator.OperatorCreationException: cannot create signer: Supplied key (null) is not a RSAPrivateKey instance
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source)
	at org.bouncycastle.cms.jcajce.JcaSimpleSignerInfoGeneratorBuilder$Helper.createContentSigner(Unknown Source)
	at org.bouncycastle.cms.jcajce.JcaSimpleSignerInfoGeneratorBuilder.build(Unknown Source)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:677)
	... 4 more
Caused by: java.security.InvalidKeyException: Supplied key (null) is not a RSAPrivateKey instance
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.DigestSignatureSpi.engineInitSign(Unknown Source)
	at java.base/java.security.Signature$Delegate.init(Signature.java:1179)
	at java.base/java.security.Signature$Delegate.chooseProvider(Signature.java:1139)
	at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1203)
	at java.base/java.security.Signature.initSign(Signature.java:546)
	... 8 more
`

**Código utilizado:**

`package org.demoiselle.signer.signer.examples;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.UnrecoverableKeyException;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.demoiselle.signer.chain.icp.brasil.provider.impl.ICPBrasilUserHomeProviderCA;
import org.demoiselle.signer.core.keystore.loader.KeyStoreLoader;
import org.demoiselle.signer.core.keystore.loader.factory.KeyStoreLoaderFactory;
import org.demoiselle.signer.policy.engine.factory.PolicyFactory.Policies;
import org.demoiselle.signer.policy.impl.cades.SignerAlgorithmEnum;
import org.demoiselle.signer.policy.impl.cades.factory.PKCS7Factory;
import org.demoiselle.signer.policy.impl.cades.pkcs7.PKCS7Signer;

public class Signer {

	private static final Logger LOGGER = Logger.getLogger(Signer.class.getName());

	public static void main(String[] args) throws Throwable {

		String textToSign = "Julian Cesar";
		String homeUser = ICPBrasilUserHomeProviderCA.PATH_HOME_USER;

		LOGGER.log(Level.INFO, "============= Iniciando aplicaÃ§Ã£o =============");

		Path p7sFilePath = Paths.get(homeUser, "textoAssinado." + Policies.AD_RB_CADES_2_2.toString() + ".p7s");
		sign(textToSign, p7sFilePath, Policies.AD_RB_CADES_2_2, SignerAlgorithmEnum.SHA256withRSA);

		/*p7sFilePath = Paths.get(homeUser, "textoAssinado." + Policies.AD_RB_CADES_2_1.toString() + ".p7s");
		sign(textToSign, p7sFilePath, Policies.AD_RB_CADES_2_1, SignerAlgorithmEnum.SHA256withRSA);

		p7sFilePath = Paths.get(homeUser, "textoAssinado." + Policies.AD_RB_CADES_2_2.toString() + ".p7s");
		sign(textToSign, p7sFilePath, Policies.AD_RB_CADES_2_2, SignerAlgorithmEnum.SHA512withRSA);*/

		LOGGER.log(Level.INFO, "============= Finalizando aplicaÃ§Ã£o =============");

	}

	public static KeyStoreLoader keyStoreLoader;
	public static KeyStore keyStore;
	public static String alias;
	public static X509Certificate certificate;
	public static PrivateKey privateKey;
	// public static PinHandler pinHandler;
	public static String password;
	public static Certificate[] certificateChain;

	public static void sign(String text, Path pathP7s, Policies police, SignerAlgorithmEnum algorithm)
			throws KeyStoreException, IOException, UnrecoverableKeyException, NoSuchAlgorithmException {

		LOGGER.log(Level.INFO, "===== " + police.toString() + " =====");

		byte[] content = text.getBytes();

		PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();

		// if (pinHandler == null) {
		// pinHandler = new PinHandler("AÃ§Ãµes");
		// }

		if (keyStoreLoader == null) {
			keyStoreLoader = KeyStoreLoaderFactory.factoryKeyStoreLoader();
			// keyStoreLoader.setCallbackHandler(pinHandler);
			keyStore = keyStoreLoader.getKeyStore();
			alias = keyStore.aliases().nextElement();
			certificate = (X509Certificate) keyStore.getCertificate(alias);
			privateKey = (PrivateKey) keyStore.getKey(alias, null);
			certificateChain = keyStore.getCertificateChain(alias);
		}

		signer.setCertificates(certificateChain);
		signer.setPrivateKey(privateKey);

		signer.setSignaturePolicy(police);
		signer.setAlgorithm(algorithm);

		byte[] sign = signer.doAttachedSign(content);

		System.out.println(">>>>>>>>>> Validando a assinatura");

		// Valida
		signer.check(content, sign);

		ByteArrayInputStream bis = new ByteArrayInputStream(sign);

		Files.copy(bis, pathP7s, java.nio.file.StandardCopyOption.REPLACE_EXISTING);

	}

}
`

**Comment by esaito** [comment]
Poderia nos informar qual o sistema operacional que está usando?
A questão da politica não é um problema, no caso ela estará sendo recuperada de forma on-line só vai ter problema se não houver conexão.
Poder fazer um teste de assinatura com o assinador do Serpro ? https://www.serpro.gov.br/assinador-digital

**Comment by wmodanez** [comment]
Remova as linhas que fazem referência a Policies.AD_RB_CADES_2.2 deixando apenas a linha abaixo:

`        Path p7sFilePath = Paths.get(homeUser, "textoAssinado." + Policies.AD_RB_CADES_2_2.toString() + ".p7s");
        sign(textToSign, p7sFilePath, Policies.AD_RB_CADES_2_2, SignerAlgorithmEnum.SHA512withRSA);`
