### ISSUE TITLE
Error trying get Keyvalue CPF

### ISSUE THREAD

**Issue by jordanorc** [demoiselle/signer#21]
Ao tentar utilizar a versão BETA1 com certificado A3, estou recebendo a seguinte exceção:

`Exception in thread "main" org.demoiselle.signer.signature.core.exception.CertificateCoreException: Error trying get Keyvalue CPF
	at org.demoiselle.signer.signature.core.extension.ICPBrasilExtensionLoader.load(ICPBrasilExtensionLoader.java:277)
	at org.demoiselle.signer.signature.core.CertificateManager.load(CertificateManager.java:111)
	at org.demoiselle.signer.signature.core.CertificateManager.load(CertificateManager.java:127)
	at br.com.telessaude.pdfsign.App.getICPBrasilCertificate(App.java:45)
	at br.com.telessaude.pdfsign.App.main(App.java:76)
Caused by: java.lang.ClassCastException: org.demoiselle.signer.signature.core.oid.OIDGeneric cannot be cast to org.demoiselle.signer.signature.core.oid.OID_2_16_76_1_3_1
	at org.demoiselle.signer.signature.core.extension.CertificateExtra.getOID_2_16_76_1_3_1(CertificateExtra.java:153)
	at org.demoiselle.signer.signature.core.extension.ICPBRSubjectAlternativeNames.<init>(ICPBRSubjectAlternativeNames.java:58)
	at org.demoiselle.signer.signature.core.extension.BasicCertificate.getICPBRSubjectAlternativeNames(BasicCertificate.java:286)
	at org.demoiselle.signer.signature.core.extension.BasicCertificate.hasCertificatePF(BasicCertificate.java:313)
	at org.demoiselle.signer.signature.core.extension.ICPBrasilExtensionLoader.load(ICPBrasilExtensionLoader.java:59)
	... 4 more`

Alguma idéia do que pode ser?

**Comment by jordanorc** [comment]
Compilei a versão 2.0.0-BETA2 e aparentemente o problema não acontece.
