### ISSUE TITLE
Modo offline não funciona

### ISSUE THREAD

**Issue by luizcgr** [demoiselle/signer#241]
Estamos tentando utilizar o modo offline para a validação de CRLs de um certificado. O modo online (default) funciona corretamente, porém, algumas vezes, não estando as listas de revogação disponíveis em suas origens, estamos bloqueando assinaturas mesmo se uma CRL ainda estiver dentro do período de validade.

Segundo a documentação ([https://www.frameworkdemoiselle.gov.br/v3/signer/docs/certificate-funcionalidades.html#d0e382](url)), caso uma CRL não exista no repositório offline, a mesma será recuperada de forma online e armazenada localmente para as próximas validações. 

> Quando o arquivo de crl se encontra com data vencida ou não existe o arquivo no diretório, o repositório Offline realiza o download do arquivo de crl e o armazena no diretório de crl.

Tanto a configuração para ativar o modo online quanto as configurações de crlIndex e crlPath estão sendo realizadas conforme a documentação. O valor de crlPath aponta para um diretório onde o usuário que executa a aplicação possui as permissões para criar, alterar e excluir arquivos. 

```java
    import org.demoiselle.signer.core.repository.Configuration;
    ...
    final Configuration config = Configuration.getInstance();
    config.setOnline(this.crlOnline);
    config.setCrlPath(this.crlPath);
    config.setCrlIndex(this.crlIndex);
```

Segue o trecho do log gerado:

```logs
   2020-03-26 14:56:32,189 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Foi(ram) encontrada(s) 0 contra-assinatura(s).
--
  | 2020-03-26 14:56:32,234 [http-nio-8180-exec-10] INFO  o.d.s.c.extension.BasicCertificate - Adicionando a url http://icp-brasil.certisign.com.br/repositorio/lcr/ACCertisign-JUSG6/LatestCRL.crl
  | 2020-03-26 14:56:32,235 [http-nio-8180-exec-10] INFO  o.d.s.c.extension.BasicCertificate - Adicionando a url http://icp-brasil.outralcr.com.br/repositorio/lcr/ACCertisign-JUSG6/LatestCRL.crl
  | 2020-03-26 14:56:32,235 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - O repositório de LCR (lista de certificados revogados)  foi criado com sucesso!.
  | 2020-03-26 14:56:32,244 [http-nio-8180-exec-10] INFO  o.d.signer.core.util.RepositoryUtil - O arquivo será gerado em: /tmp/crls/8eabf04464e86773f13dc7f0289bfb18
  | 2020-03-26 14:56:33,106 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - Foi encontrada uma LCR OffLine válida
  | 2020-03-26 14:56:33,421 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Validada a assinatura digital de sequência [1]
  | 2020-03-26 14:56:33,422 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Efetuando a verificação dos atributos assinados
  | 2020-03-26 14:56:33,429 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Data no formato: UTCTime yyMMddHHmmssz : 3/26/20, 2:56 PM
  | 2020-03-26 14:56:33,429 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Não foi encontrada a política {0}, na lista do componente.
  | 2020-03-26 14:56:33,430 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Efetuando a verificação dos atributos NÃO assinados
  | 2020-03-26 14:56:33,430 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Não foi encontrada a lista de atributos NÃO assinados no pacote PKCS7.
  | log4j:ERROR setFile(null,true) call failed.
  | java.io.FileNotFoundException: signer_core.log (Permission denied)
  | at java.base/java.io.FileOutputStream.open0(Native Method)
  | at java.base/java.io.FileOutputStream.open(Unknown Source)
  | at java.base/java.io.FileOutputStream.<init>(Unknown Source)
  | at java.base/java.io.FileOutputStream.<init>(Unknown Source)
  | at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
  | at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
  | at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
  | at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
  | at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
  | at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
  | at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
  | at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
  | at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
  | at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
  | at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
  | at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
  | at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
  | at org.apache.log4j.Logger.getLogger(Logger.java:104)
  | at org.demoiselle.signer.core.ca.manager.CAManager.<clinit>(CAManager.java:62)
  | at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESChecker.check(CAdESChecker.java:326)
  | at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESChecker.checkAttachedSignature(CAdESChecker.java:436)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.validador.ValidadorArquivoAssinado.extraiSignaturesInfo(ValidadorArquivoAssinado.java:66)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.validador.ValidadorArquivoAssinado.validaArquivoAssinado(ValidadorArquivoAssinado.java:43)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.controller.UploadHandler.handleFileUpload(UploadHandler.java:40)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.controller.AmazonS3Controller.handleFileUpload(AmazonS3Controller.java:30)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
  | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
  | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
  | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
  | at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | 2020-03-26 14:56:33 INFO  CAManager:236 - Procurando certificado no Provider: Provedor OFFLINE de cadeias ICP-Brasil  (icpbrasil.jks)
  | 2020-03-26 14:56:34 INFO  CAManager:288 - Foram encontrados 4 níveis na cadeia do provider Provedor OFFLINE de cadeias ICP-Brasil  (icpbrasil.jks)
  | 2020-03-26 14:56:34,413 [http-nio-8180-exec-10] INFO  o.d.s.p.i.c.pkcs7.impl.CAdESChecker - Verificada(s) 1 assinatura(s).
  | 2020-03-26 14:56:34,419 [http-nio-8180-exec-10] INFO  o.d.s.c.extension.BasicCertificate - Adicionando a url http://icp-brasil.certisign.com.br/repositorio/lcr/ACCertisign-JUSG6/LatestCRL.crl
  | 2020-03-26 14:56:34,419 [http-nio-8180-exec-10] INFO  o.d.s.c.extension.BasicCertificate - Adicionando a url http://icp-brasil.outralcr.com.br/repositorio/lcr/ACCertisign-JUSG6/LatestCRL.crl
  | 2020-03-26 14:56:34,419 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - O repositório de LCR (lista de certificados revogados)  foi criado com sucesso!.
  | 2020-03-26 14:56:34,421 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - Foi encontrada uma LCR OffLine válida
  | 2020-03-26 14:56:34,422 [http-nio-8180-exec-10] INFO  o.d.s.c.extension.BasicCertificate - Adicionando a url http://lcr.acjus.jus.br/acjusv5.crl
  | 2020-03-26 14:56:34,422 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - O repositório de LCR (lista de certificados revogados)  foi criado com sucesso!.
  | 2020-03-26 14:56:34,424 [http-nio-8180-exec-10] INFO  o.d.signer.core.util.RepositoryUtil - O arquivo será gerado em: /tmp/crls/adc2b57c503a9811d83f84789c44e68e
  | 2020-03-26 14:56:34,550 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - Ocorreu uma falha ao tentar remover o arquivo: /tmp/crls/adc2b57c503a9811d83f84789c44e68e
  | 2020-03-26 14:56:34,563 [http-nio-8180-exec-10] ERROR b.j.t.p.o.a.a.c.UploadHandler - Não foi possível verificar se o certificado está Revogado. Nenhuma das listas do certificado estava disponível (on-line):
  | [http://lcr.acjus.jus.br/acjusv5.crl ]
  | org.demoiselle.signer.core.exception.CertificateValidatorCRLException: Não foi possível verificar se o certificado está Revogado. Nenhuma das listas do certificado estava disponível (on-line):
  | [http://lcr.acjus.jus.br/acjusv5.crl ]
  | at org.demoiselle.signer.core.validator.CRLValidator.validate(CRLValidator.java:71)
  | at org.demoiselle.signer.core.CertificateManager.init(CertificateManager.java:161)
  | at org.demoiselle.signer.core.CertificateManager.<init>(CertificateManager.java:112)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.validador.ValidadorArquivoAssinado.validaX509Certificate(ValidadorArquivoAssinado.java:104)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.validador.ValidadorArquivoAssinado.validaCertificados(ValidadorArquivoAssinado.java:90)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.validador.ValidadorArquivoAssinado.validaArquivoAssinado(ValidadorArquivoAssinado.java:46)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.controller.UploadHandler.handleFileUpload(UploadHandler.java:40)
  | at br.jus.tjdft.pje.office.amazons3.adapterservice.controller.AmazonS3Controller.handleFileUpload(AmazonS3Controller.java:30)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
  | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
  | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
  | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
  | at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
  | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | 2020-03-26 14:56:34,742 [http-nio-8180-exec-10] INFO  b.j.t.p.o.a.a.c.UploadHandler - Requisição de upload processada. resultado=erro, duracao=3482 ms
```

Existe alguma configuração adicional que precisa ser feita para que o modo offline funcione conforme a documentação? Existe uma indicação de falha na gravação de log, porém, no modo online o mesmo log é gerado, mas a assinatura e respectivas validações são processadas corretamente.

Poderiam ajudar?

Agradeço desde já!

**Comment by esaito** [comment]
Há um trecho da log:

O arquivo será gerado em: /tmp/crls/adc2b57c503a9811d83f84789c44e68e
  | 2020-03-26 14:56:34,550 [http-nio-8180-exec-10] INFO  o.d.s.c.r.OffLineCRLRepository - Ocorreu uma falha ao tentar remover o arquivo: /tmp/crls/adc2b57c503a9811d83f84789c44e68e

É provável que seja falta de permissão. Dependendo do servidor de aplicações que está executando há um "usuário" que roda o processo. As configurações "default" /tmp/ (padrão linux), poderiam ser modificadas para apontar para um diretório do usuário que executa o servidor de aplicações. (ex: /home/"usuario_do_SA"/lcr_off_line/)

**Comment by esaito** [comment]
A discussão tem mais de 1 mês sem mensagens, será fechada.
